In [4]:
import pandas as pd
import plotly.graph_objects as go
import utils

In [5]:
ma_test_res = pd.read_pickle(utils.get_ma_test_results_data_filename())
all_trades = pd.read_pickle(utils.get_all_trades_filename())

In [6]:
all_trades.shape

(66593, 13)

In [11]:
ma_test_res.head()

      pair  num_trades  total_gain  mashort  malong
0  GBP_USD         561       188.5        4       8
1  GBP_USD         307       231.6        4      16
2  GBP_USD         275       362.2        8      16
3  GBP_USD         209      -116.1        4      32
4  GBP_USD         159      -480.8        8      32

In [10]:
ma_test_res.columns

Index(['pair', 'num_trades', 'total_gain', 'mashort', 'malong'], dtype='object')

In [9]:
ma_test_res = ma_test_res[['pair', 'num_trades', 'total_gain', 'mashort', 'malong']]

In [19]:
ma_test_res["CROSS"] = "MA_" + ma_test_res.mashort.map(str) + "_" + ma_test_res.malong.map(str)

In [20]:
ma_test_res.head()

      pair  num_trades  total_gain  mashort  malong    CROSS
0  GBP_USD         561       188.5        4       8   MA_4_8
1  GBP_USD         307       231.6        4      16  MA_4_16
2  GBP_USD         275       362.2        8      16  MA_8_16
3  GBP_USD         209      -116.1        4      32  MA_4_32
4  GBP_USD         159      -480.8        8      32  MA_8_32

In [21]:
df_all_gains = ma_test_res.groupby(by=["CROSS", "mashort", "malong"], as_index=False).sum()

In [22]:
df_all_gains

        CROSS  mashort  malong  num_trades  total_gain
0   MA_16_128       16     128        1064     -7708.0
1   MA_16_256       16     256         687     -5279.8
2    MA_16_32       16      32        2842      -560.1
3    MA_16_64       16      64        1654      -941.6
4    MA_16_96       16      96        1272     -2801.0
5   MA_24_128       24     128         932     -6944.9
6   MA_24_256       24     256         579     -5603.4
7    MA_24_32       24      32        3225     -5073.9
8    MA_24_64       24      64        1463      1106.4
9    MA_24_96       24      96        1103     -3259.2
10  MA_32_128       32     128         828     -5723.7
11  MA_32_256       32     256         508     -5333.4
12   MA_32_64       32      64        1404      2992.0
13   MA_32_96       32      96        1005     -1738.0
14   MA_4_128        4     128        1901     -5806.6
15    MA_4_16        4      16        6626     -2308.0
16   MA_4_256        4     256        1351     -6439.3
17    MA_4_32        4      32        4129      -376.4
18    MA_4_64        4      64        2712      -430.5
19     MA_4_8        4       8       11845     -1365.7
20    MA_4_96        4      96        2243     -3497.2
21  MA_64_128       64     128         718     -6615.3
22  MA_64_256       64     256         373     -7561.1
23   MA_64_96       64      96        1018     -8042.0
24   MA_8_128        8     128        1418     -6865.8
25    MA_8_16        8      16        5852       263.4
26   MA_8_256        8     256         952     -6784.9
27    MA_8_32        8      32        3219      1313.7
28    MA_8_64        8      64        2018      -891.7
29    MA_8_96        8      96        1652     -4592.9

In [23]:
df_all_gains.sort_values(by="total_gain", ascending=False, inplace=True)

In [25]:
df_all_gains

        CROSS  mashort  malong  num_trades  total_gain
12   MA_32_64       32      64        1404      2992.0
27    MA_8_32        8      32        3219      1313.7
8    MA_24_64       24      64        1463      1106.4
25    MA_8_16        8      16        5852       263.4
17    MA_4_32        4      32        4129      -376.4
18    MA_4_64        4      64        2712      -430.5
2    MA_16_32       16      32        2842      -560.1
28    MA_8_64        8      64        2018      -891.7
3    MA_16_64       16      64        1654      -941.6
19     MA_4_8        4       8       11845     -1365.7
13   MA_32_96       32      96        1005     -1738.0
15    MA_4_16        4      16        6626     -2308.0
4    MA_16_96       16      96        1272     -2801.0
9    MA_24_96       24      96        1103     -3259.2
20    MA_4_96        4      96        2243     -3497.2
29    MA_8_96        8      96        1652     -4592.9
7    MA_24_32       24      32        3225     -5073.9
1   MA_16_256       16     256         687     -5279.8
11  MA_32_256       32     256         508     -5333.4
6   MA_24_256       24     256         579     -5603.4
10  MA_32_128       32     128         828     -5723.7
14   MA_4_128        4     128        1901     -5806.6
16   MA_4_256        4     256        1351     -6439.3
21  MA_64_128       64     128         718     -6615.3
26   MA_8_256        8     256         952     -6784.9
24   MA_8_128        8     128        1418     -6865.8
5   MA_24_128       24     128         932     -6944.9
22  MA_64_256       64     256         373     -7561.1
0   MA_16_128       16     128        1064     -7708.0
23   MA_64_96       64      96        1018     -8042.0

In [26]:
ma_32_64 = ma_test_res[ma_test_res["CROSS"]=="MA_32_64"].copy()

In [27]:
ma_32_64

        pair  num_trades  total_gain  mashort  malong     CROSS
11   GBP_USD          70        41.4       32      64  MA_32_64
41   GBP_CAD          67       -14.1       32      64  MA_32_64
71   GBP_JPY          62       700.4       32      64  MA_32_64
101  GBP_NZD          69       273.4       32      64  MA_32_64
131  GBP_CHF          76      -821.6       32      64  MA_32_64
161  EUR_GBP          64      -477.2       32      64  MA_32_64
191  EUR_USD          70         7.4       32      64  MA_32_64
221  EUR_CAD          65      -126.4       32      64  MA_32_64
251  EUR_JPY          64       179.5       32      64  MA_32_64
281  EUR_NZD          72       447.5       32      64  MA_32_64
311  EUR_CHF          63      -137.3       32      64  MA_32_64
341  USD_CAD          66       618.1       32      64  MA_32_64
371  USD_JPY          67       229.0       32      64  MA_32_64
401  USD_CHF          74      -638.7       32      64  MA_32_64
431  CAD_JPY          64       859.0       32      64  MA_32_64
461  CAD_CHF          72      -494.3       32      64  MA_32_64
491  NZD_USD          70      -172.8       32      64  MA_32_64
521  NZD_CAD          72       378.1       32      64  MA_32_64
551  NZD_JPY          56      1259.7       32      64  MA_32_64
581  NZD_CHF          62       544.5       32      64  MA_32_64
611  CHF_JPY          59       336.4       32      64  MA_32_64

In [28]:
ma_32_64.sort_values(by="total_gain", ascending=False, inplace=True)

In [29]:
ma_32_64

        pair  num_trades  total_gain  mashort  malong     CROSS
551  NZD_JPY          56      1259.7       32      64  MA_32_64
431  CAD_JPY          64       859.0       32      64  MA_32_64
71   GBP_JPY          62       700.4       32      64  MA_32_64
341  USD_CAD          66       618.1       32      64  MA_32_64
581  NZD_CHF          62       544.5       32      64  MA_32_64
281  EUR_NZD          72       447.5       32      64  MA_32_64
521  NZD_CAD          72       378.1       32      64  MA_32_64
611  CHF_JPY          59       336.4       32      64  MA_32_64
101  GBP_NZD          69       273.4       32      64  MA_32_64
371  USD_JPY          67       229.0       32      64  MA_32_64
251  EUR_JPY          64       179.5       32      64  MA_32_64
11   GBP_USD          70        41.4       32      64  MA_32_64
191  EUR_USD          70         7.4       32      64  MA_32_64
41   GBP_CAD          67       -14.1       32      64  MA_32_64
221  EUR_CAD          65      -126.4       32      64  MA_32_64
311  EUR_CHF          63      -137.3       32      64  MA_32_64
491  NZD_USD          70      -172.8       32      64  MA_32_64
161  EUR_GBP          64      -477.2       32      64  MA_32_64
461  CAD_CHF          72      -494.3       32      64  MA_32_64
401  USD_CHF          74      -638.7       32      64  MA_32_64
131  GBP_CHF          76      -821.6       32      64  MA_32_64

In [33]:
total_p = len(ma_32_64.pair.unique())

In [35]:
total_p

21

In [34]:
ma_32_64[ma_32_64.total_gain>0].shape[0]

13

In [43]:
df_all_gains.CROSS.unique().shape[0]

30

In [50]:
percent_good_list = []


for cross in df_all_gains.CROSS.unique():
    df_temp = ma_test_res[ma_test_res.CROSS==cross]
    # print(cross)
    # print(df_temp.head())
    total_p = df_temp.shape[0]
    n_good = df_temp[df_temp.total_gain>0].shape[0]
    percent = (n_good/total_p)*100
    text = f"Cross: {cross:12} Number of pairs: {total_p} Number of good pairs: {n_good:4} Percentage of good pairs: {percent:4.0f}%"
    print(text)
    percent_good_list.append(
        {
            'Desc'      : text,
            'Percent'   : percent
        }
        
    )

df_percent_good = pd.DataFrame(percent_good_list)

Cross: MA_32_64     Number of pairs: 21 Number of good pairs:   13 Percentage of good pairs:   62%
Cross: MA_8_32      Number of pairs: 21 Number of good pairs:   11 Percentage of good pairs:   52%
Cross: MA_24_64     Number of pairs: 21 Number of good pairs:   12 Percentage of good pairs:   57%
Cross: MA_8_16      Number of pairs: 21 Number of good pairs:   14 Percentage of good pairs:   67%
Cross: MA_4_32      Number of pairs: 21 Number of good pairs:   10 Percentage of good pairs:   48%
Cross: MA_4_64      Number of pairs: 21 Number of good pairs:    7 Percentage of good pairs:   33%
Cross: MA_16_32     Number of pairs: 21 Number of good pairs:   11 Percentage of good pairs:   52%
Cross: MA_8_64      Number of pairs: 21 Number of good pairs:    8 Percentage of good pairs:   38%
Cross: MA_16_64     Number of pairs: 21 Number of good pairs:    9 Percentage of good pairs:   43%
Cross: MA_4_8       Number of pairs: 21 Number of good pairs:   11 Percentage of good pairs:   52%
Cross: MA_32_96     Number of pairs: 21 Number of good pairs:    8 Percentage of good pairs:   38%
Cross: MA_4_16      Number of pairs: 21 Number of good pairs:   10 Percentage of good pairs:   48%
Cross: MA_16_96     Number of pairs: 21 Number of good pairs:    9 Percentage of good pairs:   43%
Cross: MA_24_96     Number of pairs: 21 Number of good pairs:    9 Percentage of good pairs:   43%
Cross: MA_4_96      Number of pairs: 21 Number of good pairs:    8 Percentage of good pairs:   38%
Cross: MA_8_96      Number of pairs: 21 Number of good pairs:    7 Percentage of good pairs:   33%
Cross: MA_24_32     Number of pairs: 21 Number of good pairs:    6 Percentage of good pairs:   29%
Cross: MA_16_256    Number of pairs: 21 Number of good pairs:    5 Percentage of good pairs:   24%
Cross: MA_32_256    Number of pairs: 21 Number of good pairs:    7 Percentage of good pairs:   33%
Cross: MA_24_256    Number of pairs: 21 Number of good pairs:    3 Percentage of good pairs:   14%
Cross: MA_32_128    Number of pairs: 21 Number of good pairs:    7 Percentage of good pairs:   33%
Cross: MA_4_128     Number of pairs: 21 Number of good pairs:    8 Percentage of good pairs:   38%
Cross: MA_4_256     Number of pairs: 21 Number of good pairs:    6 Percentage of good pairs:   29%
Cross: MA_64_128    Number of pairs: 21 Number of good pairs:    4 Percentage of good pairs:   19%
Cross: MA_8_256     Number of pairs: 21 Number of good pairs:    6 Percentage of good pairs:   29%
Cross: MA_8_128     Number of pairs: 21 Number of good pairs:    5 Percentage of good pairs:   24%
Cross: MA_24_128    Number of pairs: 21 Number of good pairs:    7 Percentage of good pairs:   33%
Cross: MA_64_256    Number of pairs: 21 Number of good pairs:    7 Percentage of good pairs:   33%
Cross: MA_16_128    Number of pairs: 21 Number of good pairs:    8 Percentage of good pairs:   38%
Cross: MA_64_96     Number of pairs: 21 Number of good pairs:    5 Percentage of good pairs:   24%

In [52]:
df_percent_good.sort_values(by="Percent", ascending=False)

                                                 Desc    Percent
3   Cross: MA_8_16      Number of pairs: 21 Number...  66.666667
0   Cross: MA_32_64     Number of pairs: 21 Number...  61.904762
2   Cross: MA_24_64     Number of pairs: 21 Number...  57.142857
6   Cross: MA_16_32     Number of pairs: 21 Number...  52.380952
1   Cross: MA_8_32      Number of pairs: 21 Number...  52.380952
9   Cross: MA_4_8       Number of pairs: 21 Number...  52.380952
11  Cross: MA_4_16      Number of pairs: 21 Number...  47.619048
4   Cross: MA_4_32      Number of pairs: 21 Number...  47.619048
8   Cross: MA_16_64     Number of pairs: 21 Number...  42.857143
12  Cross: MA_16_96     Number of pairs: 21 Number...  42.857143
13  Cross: MA_24_96     Number of pairs: 21 Number...  42.857143
28  Cross: MA_16_128    Number of pairs: 21 Number...  38.095238
7   Cross: MA_8_64      Number of pairs: 21 Number...  38.095238
10  Cross: MA_32_96     Number of pairs: 21 Number...  38.095238
14  Cross: MA_4_96      Number of pairs: 21 Number...  38.095238
21  Cross: MA_4_128     Number of pairs: 21 Number...  38.095238
20  Cross: MA_32_128    Number of pairs: 21 Number...  33.333333
27  Cross: MA_64_256    Number of pairs: 21 Number...  33.333333
26  Cross: MA_24_128    Number of pairs: 21 Number...  33.333333
15  Cross: MA_8_96      Number of pairs: 21 Number...  33.333333
18  Cross: MA_32_256    Number of pairs: 21 Number...  33.333333
5   Cross: MA_4_64      Number of pairs: 21 Number...  33.333333
22  Cross: MA_4_256     Number of pairs: 21 Number...  28.571429
24  Cross: MA_8_256     Number of pairs: 21 Number...  28.571429
16  Cross: MA_24_32     Number of pairs: 21 Number...  28.571429
25  Cross: MA_8_128     Number of pairs: 21 Number...  23.809524
17  Cross: MA_16_256    Number of pairs: 21 Number...  23.809524
29  Cross: MA_64_96     Number of pairs: 21 Number...  23.809524
23  Cross: MA_64_128    Number of pairs: 21 Number...  19.047619
19  Cross: MA_24_256    Number of pairs: 21 Number...  14.285714

In [62]:
best_crosses = df_all_gains.CROSS.unique()[[0,2,3]]

In [63]:
best_crosses

array(['MA_32_64', 'MA_24_64', 'MA_8_16'], dtype=object)

In [64]:
percent_good_list = []


for cross in best_crosses:
    df_temp = ma_test_res[ma_test_res.CROSS==cross]
    # print(cross)
    # print(df_temp.head())
    total_p = df_temp.shape[0]
    n_good = df_temp[df_temp.total_gain>0].shape[0]
    percent = (n_good/total_p)*100
    text = f"Cross: {cross:12} Number of pairs: {total_p} Number of good pairs: {n_good:4} Percentage of good pairs: {percent:4.0f}%"
    print(text)
    percent_good_list.append(
        {
            'Desc'      : text,
            'Percent'   : percent
        }
        
    )

df_percent_good2 = pd.DataFrame(percent_good_list).sort_values(by="Percent", ascending=False)
print(df_percent_good2)

Cross: MA_32_64     Number of pairs: 21 Number of good pairs:   13 Percentage of good pairs:   62%
Cross: MA_24_64     Number of pairs: 21 Number of good pairs:   12 Percentage of good pairs:   57%
Cross: MA_8_16      Number of pairs: 21 Number of good pairs:   14 Percentage of good pairs:   67%
                                                Desc    Percent
2  Cross: MA_8_16      Number of pairs: 21 Number...  66.666667
0  Cross: MA_32_64     Number of pairs: 21 Number...  61.904762
1  Cross: MA_24_64     Number of pairs: 21 Number...  57.142857

In [67]:
df_best_crosses = ma_test_res[(ma_test_res.CROSS.isin(best_crosses)) & (ma_test_res.total_gain>0)].copy()

In [68]:
df_best_crosses

        pair  num_trades  total_gain  mashort  malong     CROSS
2    GBP_USD         275       362.2        8      16   MA_8_16
11   GBP_USD          70        41.4       32      64  MA_32_64
40   GBP_CAD          73       262.4       24      64  MA_24_64
62   GBP_JPY         277       364.1        8      16   MA_8_16
70   GBP_JPY          62      1120.5       24      64  MA_24_64
71   GBP_JPY          62       700.4       32      64  MA_32_64
101  GBP_NZD          69       273.4       32      64  MA_32_64
182  EUR_USD         291         7.4        8      16   MA_8_16
190  EUR_USD          60       107.9       24      64  MA_24_64
191  EUR_USD          70         7.4       32      64  MA_32_64
212  EUR_CAD         274       524.0        8      16   MA_8_16
242  EUR_JPY         261       453.9        8      16   MA_8_16
250  EUR_JPY          66       106.5       24      64  MA_24_64
251  EUR_JPY          64       179.5       32      64  MA_32_64
272  EUR_NZD         279       487.6        8      16   MA_8_16
280  EUR_NZD          82       333.5       24      64  MA_24_64
281  EUR_NZD          72       447.5       32      64  MA_32_64
332  USD_CAD         274       187.6        8      16   MA_8_16
340  USD_CAD          72        98.9       24      64  MA_24_64
341  USD_CAD          66       618.1       32      64  MA_32_64
362  USD_JPY         268       340.1        8      16   MA_8_16
370  USD_JPY          59       358.2       24      64  MA_24_64
371  USD_JPY          67       229.0       32      64  MA_32_64
422  CAD_JPY         267       304.2        8      16   MA_8_16
430  CAD_JPY          74       634.3       24      64  MA_24_64
431  CAD_JPY          64       859.0       32      64  MA_32_64
482  NZD_USD         268       145.4        8      16   MA_8_16
512  NZD_CAD         266       396.6        8      16   MA_8_16
520  NZD_CAD          70       276.6       24      64  MA_24_64
521  NZD_CAD          72       378.1       32      64  MA_32_64
542  NZD_JPY         262       602.6        8      16   MA_8_16
550  NZD_JPY          64       778.2       24      64  MA_24_64
551  NZD_JPY          56      1259.7       32      64  MA_32_64
572  NZD_CHF         280       127.4        8      16   MA_8_16
580  NZD_CHF          74       131.7       24      64  MA_24_64
581  NZD_CHF          62       544.5       32      64  MA_32_64
602  CHF_JPY         280       221.1        8      16   MA_8_16
610  CHF_JPY          60       235.0       24      64  MA_24_64
611  CHF_JPY          59       336.4       32      64  MA_32_64

In [73]:
df_best_crosses.pair.value_counts()

GBP_JPY    3
EUR_USD    3
EUR_JPY    3
EUR_NZD    3
USD_CAD    3
USD_JPY    3
CAD_JPY    3
NZD_CAD    3
NZD_JPY    3
NZD_CHF    3
CHF_JPY    3
GBP_USD    2
GBP_CAD    1
GBP_NZD    1
EUR_CAD    1
NZD_USD    1
Name: pair, dtype: int64

In [78]:
our_pairs = list(df_best_crosses.pair.value_counts()[0:11].index)

In [79]:
our_pairs

['GBP_JPY',
 'EUR_USD',
 'EUR_JPY',
 'EUR_NZD',
 'USD_CAD',
 'USD_JPY',
 'CAD_JPY',
 'NZD_CAD',
 'NZD_JPY',
 'NZD_CHF',
 'CHF_JPY']